def GIT_REPO_URL = 'https://github.com/vivihuang/simple-node-js-react-npm-app'
def GIT_BRANCH = 'master'

// def commit_version = '7fc3dafdc89bee14120294e2a24911c8299e5654'

pipeline {
  agent {
    docker {
      image 'node:8-alpine'
      args '-p 4000:4000'
    }
  }
  parameters {
    string(defaultValue: '', description: 'Please input git commit version.', name: 'commit_version')
  }
  stages {
    stage('Checkout'){
      steps {
        script {
          if (commit_version.trim().equals('')) {
            checkout scm
          } else {
            echo 'fdfdfddsfdsfsd'
            echo commit_version;
            checkout scm: [$class: 'GitSCM', userRemoteConfigs: [[url: GIT_REPO_URL]], branches: [[name: commit_version]]], poll: false
          }
        }
      }
    }

    stage('Build') {
      steps {
        sh 'node -v'
        sh 'npm prune'
        sh 'npm install'
      }
    }

    stage('Deploy to QA') {
      steps {
        sh './jenkins/scripts/deliver.sh'
        timeout(time: 3, unit: 'MINUTES') {
          sh './jenkins/scripts/kill.sh'
        }
      }
    }
  }
}
