pipeline {
    agent {
        docker {
            image 'node:8-alpine'
            args '-p 3000:3000'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'node -v'
                sh 'npm prune'
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }

        stage('Deploy to DEV') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                timeout(time: 30, unit: 'SECONDS') {
                  sh './jenkins/scripts/kill.sh'
                }
            }
        }
    }
}
